woowacourse-teams/2021-drop-the-code

frontend/babel.config.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/Header/Header.stories.tsx, frontend/src/components/Header/Header.tsx, frontend/src/components/shared/Flexbox/Flexbox.tsx, frontend/src/utils/constants/size.ts
- babel plugin styled components 설치
- 헤더 컴포넌트 구현
- 플렉스 박스 컴포넌트 구현
=> 헤더, 플렉스 박스 컴포넌트 구현

frontend/src/components/shared/Button/Button.stories.tsx, frontend/src/components/shared/Select/Select.stories.tsx, frontend/src/components/shared/Select/Select.tsx
- 셀렉트 컴포넌트 구현
- 스토리북 shared 컴포넌트 story 분기
=> 셀렉트 컴포넌트 구현

frontend/public/index.html, frontend/src/components/GlobalStyle/GlobalStyle.tsx, frontend/src/components/shared/Chip/Chip.tsx
- spoqa-han-sans 에서 IBMPlexSansKR-Regular로 변경한다.
- chip의 font-weight값을 변경한다. (600 -> 300)
=> 폰트를 IBMPlexSansKR-Regular으로 변경

frontend/src/components/CareerPicker/CareerPicker.stories.tsx, frontend/src/components/CareerPicker/CareerPicker.tsx, frontend/src/components/FloatingMenuButton/FloatingMenuButton.tsx, frontend/src/components/GlobalStyle/GlobalStyle.tsx, frontend/src/components/MenuItemButton/MenuItemButton.stories.tsx, frontend/src/components/MenuItemButton/MenuItemButton.tsx, frontend/src/components/shared/Button/Button.tsx, frontend/src/pages/Main/Main.tsx
- 메뉴 버튼 아이템 컴포넌트와 career-picker와 컴포넌트를 조합하여 경력 필터링 기능을 구현
- 플로팅 메뉴 컴포넌트 네이밍 메뉴 버튼 아이템 컴포넌트로 수정하였습니다!!
=> CareerPicker 컴포넌트 구현

frontend/babel.config.json, frontend/package-lock.json, frontend/package.json, frontend/webpack.common.ts, frontend/webpack.dev.ts
개발 생산성을 위해 개발환경에서만 동작하도록 refresh-plugin을 추가하였습니다!
=> refresh plugin 추가

frontend/.storybook/main.js
- fastRefresh 옵션을 통해 스토리북에서 react-refresh 플러그인이 동작하도록 수정
=> 스토리북 환경에서 react-refresh 플러그인 관련 설정 추가

backend/src/main/java/com/wootech/dropthecode/DropTheCodeApplication.java, backend/src/main/java/com/wootech/dropthecode/config/JpaConfig.java
=> fix: JPA Auditing 설정 추가

.husky/pre-commit, frontend/.lintstagedrc.json, frontend/package-lock.json, frontend/package.json
- pre-commit단계에 lint-staged 실행
- lint-staged설정을 통해  staged된 파일 prettier와 eslint로 코드 수정후 커밋 진행
=> chore: 커밋 전 husky, lint-staged 코드를 수정하는 깃훅 설정

frontend/.storybook/preview.js, frontend/src/apis/review.ts, frontend/src/components/Auth/OAuth/GithubOAuth.tsx, frontend/src/components/MenuItemButton/MenuItemButton.tsx, frontend/src/components/ModalProvider/Modal.tsx, frontend/src/hooks/useLanguageList.ts, frontend/src/hooks/useReviewerList.ts, frontend/src/index.tsx, frontend/src/pages/Main/LanguageList/LanguageList.tsx, frontend/src/pages/Main/Main.tsx, frontend/src/pages/Main/ReviewerList/ReviewerList.tsx, frontend/src/pages/RedirectOAuth/RedirectOAuth.tsx, frontend/src/pages/ReviewRequest/ReviewRequest.tsx, frontend/src/pages/ReviewerDetail/ReviewRequest.stories.tsx, frontend/src/pages/ReviewerDetail/ReviewRequest/ReviewRequest.tsx, frontend/src/pages/ReviewerDetail/ReviewerDetail.tsx, frontend/src/pages/ReviewerRegister/ReviewerRegister.tsx, frontend/src/types/review.ts, frontend/src/utils/constants/message.ts, frontend/src/utils/constants/route.ts, frontend/src/utils/constants/standard.ts, frontend/src/utils/validators/reviewRequestValidators.ts, frontend/src/utils/validators/reviewerRegisterValidators.ts
=> 리뷰 요청 모달 UI 및 기능 구현 및 스토리 작성

frontend/src/components/MenuItemButton/MenuItemButton.tsx, frontend/src/components/shared/Navigation/Navigation.tsx, frontend/src/types/styled/common.d.ts, frontend/src/utils/constants/size.ts, frontend/src/utils/constants/theme.ts
헤더의 z-index 값이 잘못되어 모달의 딤드영역 위에 나타나던 문제 수정
=> 헤더의 z-index 제거 및 테마로 z-index 관리

frontend/src/apis/review.ts, frontend/src/components/GlobalStyle/GlobalStyle.tsx, frontend/src/components/MenuItemButton/MenuItemButton.tsx, frontend/src/components/Review/ReviewCard.stories.tsx, frontend/src/components/Review/ReviewCard.tsx, frontend/src/components/Reviewer/ReviewerCard.tsx, frontend/src/pages/History/History.stories.tsx, frontend/src/pages/History/History.tsx, frontend/src/pages/History/ReviewList/ReviewList.tsx, frontend/src/pages/ReviewDetail/ReviewDetail.tsx, frontend/src/pages/ReviewHistory/ReviewHistory.tsx, frontend/src/types/review.d.ts, frontend/src/types/review.ts, frontend/src/utils/constants/path.ts, frontend/src/utils/constants/route.ts, frontend/src/utils/formatter.ts
- 로그인 응답 수정후 api 호출 코드 변경 필요
- accessToken을 헤더에 추가하고, 만료된 경우 갱신 및 재 요청 로직 필요
=> 히스토리 페이지 UI , 스토리, 기능 구현

frontend/src/components/FormProvider/FormProvider.tsx, frontend/src/components/FormProvider/InputField.tsx, frontend/src/components/FormProvider/SubmitButton.tsx, frontend/src/components/FormProvider/TextareaField.tsx, frontend/src/components/Review/ReviewRequest/ReviewRequest.tsx, frontend/src/components/shared/Button/Button.stories.tsx, frontend/src/components/shared/Button/Button.tsx, frontend/src/components/shared/Input/Input.stories.tsx, frontend/src/components/shared/Input/Input.tsx, frontend/src/components/shared/Textarea/Textarea.stories.tsx, frontend/src/components/shared/Textarea/Textarea.tsx, frontend/src/hooks/useFormContext.ts, frontend/src/pages/ReviewDetail/ReviewDetail.stories.tsx, frontend/src/pages/ReviewerRegister/ReviewerRegister.tsx
- button disabled 처리 및 UI 추가
- input, textarea의 유효성 여부에 따라 border 색 변경
- FormProvider의 setState함수의 인자를 updater로 변경
=> 폼 유효성에 따른 UI 추가

backend/src/main/java/com/wootech/dropthecode/domain/Member.java, backend/src/main/resources/application-prod_create.properties, backend/src/main/resources/application-prod_insert.properties
* 리뷰를 갖고 있는 Member 삭제가 안되는 오류 수정
* Cascade 옵션 추가 -> DB 변경 필요
* 배포 편리를 위해 "prod-create", "prod-insert" 프로필을 추가하여 DB 생성, DB 초기 데이터 입력을 편리하게 할 수 있도록 추가
=> Member 삭제 기능 오류 수정  및 배포 관련 설정 추가

backend/src/main/java/com/wootech/dropthecode/exception/GlobalExceptionHandler.java, backend/src/main/resources/static/docs/api.html
얘기해야 되는 것
1. 리뷰어 목록 조회의 filter 메서드에서 `@RequestParam(defalutValue = "0") Integer career`:
career가 null로 들어왔을 때 예외 처리가 안 되지 않을까? 
defaultValue 옵션을 두는 순간 required 옵션 값은 false가 된다.
—> `MissingServletRequestParameterException` 이 발생하지 않기 때문에 GlobalExceptionHandler에서 잡아줘봤자일듯?
2. Exception.class 잡는 핸들러 추가
=> refactor: 에러 메세지 배열 형태에서 객체로 변경

backend/src/main/java/com/wootech/dropthecode/domain/Review.java, backend/src/main/java/com/wootech/dropthecode/util/DataInitializer.java, backend/src/main/resources/application-local.properties
=> feat: review 데이터 초기화 코드 추가

frontend/src/App.tsx, frontend/src/apis/apiClient.ts, frontend/src/apis/auth.ts, frontend/src/components/Auth/AuthProvider/AuthProvider.tsx, frontend/src/components/Review/ReviewInfoContainer/ReviewInfoContainer.tsx, frontend/src/components/Review/ReviewList/ReviewList.tsx, frontend/src/components/Review/ReviewRequest/ReviewRequest.tsx, frontend/src/components/Reviewer/ReviewerFloatingBox/ReviewerFloatingBox.tsx, frontend/src/hooks/useLocalStorage.ts, frontend/src/hooks/useRevalidate.ts, frontend/src/index.tsx, frontend/src/pages/RedirectOAuth/RedirectOAuth.tsx, frontend/src/pages/ReviewerRegister/ReviewerRegister.tsx, frontend/src/types/auth.d.ts
- useLocalstorage 추가
- useRevalidate 추가
=> 토큰 관리, 토큰 갱신, 재요청 기능 구현

backend/src/main/java/com/wootech/dropthecode/domain/TeacherProfile.java, backend/src/main/java/com/wootech/dropthecode/util/DataInitializer.java
* 반복문으로 Member Id 지정해주는 코드 추가
* @TaewanKimmmm 파피 피드백 적용
* local properties에서 ddl-auto create으로 변경
* DB DataInitializer ActiveProfiles에 "local" 추가
* 실행하면 DB 초기화 됨
* 코드 원상 복구
* 서버에 있는 Jenkins-init-deploy.sh 실행 -> ActiveProfiles가 "prod-init"으로 설정되어 있음
* 실행하면 DB 초기화 됨
* 다시 Jenkins-deploy.sh 실행
=> TeacherProfilie DB에 Member ID 적용되지 않는 버그 수정

backend/src/main/java/com/wootech/dropthecode/util/DataInitializer.java
* 영속성 유지를 위해 @Transactional 적용
* JPA 마스터 에어!! - @KJunseo
=> 영속성 유지를 위해 @Transactional 적용

frontend/.storybook/preview.js, frontend/package-lock.json, frontend/package.json, frontend/src/assets/close.svg, frontend/src/components/MenuItemButton/MenuItemButton.tsx, frontend/src/components/ToastProvider/Toast.stories.tsx, frontend/src/components/ToastProvider/Toast.tsx, frontend/src/components/ToastProvider/ToastButton.stories.tsx, frontend/src/components/ToastProvider/ToastProvider.tsx, frontend/src/components/Transititon/Transition.tsx, frontend/src/components/shared/Chip/Chip.tsx, frontend/src/components/shared/Input/Input.tsx, frontend/src/components/shared/Textarea/Textarea.tsx, frontend/src/hooks/useToastContext.ts, frontend/src/types/styled/common.d.ts, frontend/src/utils/constants/theme.ts
- Transition 컴포넌트 구현
- ToastProvider 구현
- success, error 테마 색상 추가
=> 토스트 컴포넌트 구현

frontend/src/types/styled/common.d.ts, frontend/src/utils/constants/theme.ts
=> merge에서 제외된 z-index 다시 설정

backend/src/main/java/com/wootech/dropthecode/controller/ReviewController.java
ReviewController 응답 헤더의 URI 수정
=> ReviewController 응답 헤더의 URI 수정

backend/src/main/java/com/wootech/dropthecode/controller/ReviewController.java, backend/src/main/java/com/wootech/dropthecode/service/ReviewService.java, backend/src/test/java/com/wootech/dropthecode/controller/ReviewControllerTest.java, backend/src/test/java/com/wootech/dropthecode/controller/auth/AuthenticationInterceptorTest.java
=> 서비스 반환 값 수정에 따른 테스트 코드 수정

frontend/package-lock.json, frontend/src/__mock__/data/auth.ts, frontend/src/__mock__/fileMock.ts, frontend/src/__mock__/server.ts, frontend/src/__mock__/utils/mockingAuth.ts, frontend/src/__mock__/utils/testUtils.tsx, frontend/src/components/Header/Header.test.tsx, frontend/src/components/Review/ReviewInfoContainer/ReviewInfoContainer.tsx, frontend/src/components/Reviewer/ReviewerInfoContainer/ReviewerInfoContainer.tsx, frontend/src/pages/History/History.tsx, frontend/src/pages/Main/Main.test.tsx, frontend/src/setupTests.ts, frontend/src/types/review.d.ts
- 헤더 컴포넌트
- 로그인/비로그인 상태에 따른 렌더링
- 로그인 되어있으면 로그아웃 버튼 렌더링 로그인X
- 로그아웃 되어있으면 로그인 버튼 렌더링 로그아웃X
- Role에 따른 버튼 렌더링
- 학생이면 리뷰어 등록하기 버튼 렌더링
- 리뷰어이면 리뷰어 등록하기 버튼 렌더링X
- 매번 테스트 이후 리액트 쿼리 캐시 무효화
=> 헤더 컴포넌트 테스트

frontend/src/components/Language/SpecPicker.tsx
- 선택된 언어, 기술 색상 구별되도록 변경
- max-width 제거
=> 리뷰어 등록 페이지 선택된 언어, 기술스택 ui 개선

backend/src/main/java/com/wootech/dropthecode/domain/Member.java
* data 초기화 email, name 바꿔서 들어가게 하는 생성자 변경
=> data 초기화 email, name 바뀌는 오류 수정

backend/src/docs/asciidoc/api.adoc, backend/src/main/java/com/wootech/dropthecode/controller/MemberController.java, backend/src/main/java/com/wootech/dropthecode/dto/response/TeacherPaginationResponse.java, backend/src/main/java/com/wootech/dropthecode/dto/response/TeacherProfileResponse.java, backend/src/main/java/com/wootech/dropthecode/dto/response/TechSpecResponse.java, backend/src/main/java/com/wootech/dropthecode/repository/TeacherFilterRepositoryImpl.java, backend/src/test/java/com/wootech/dropthecode/controller/auth/AuthenticationInterceptorTest.java
- QuerydslRepositorySupport에서 Querydsl4RepositorySupport로 변경
=> 리뷰어 단일 조회 문서화 및 목록 조회 정렬 클래스 변경

backend/src/main/generated/com/wootech/dropthecode/domain/QMember.java, backend/src/main/java/com/wootech/dropthecode/domain/Member.java, backend/src/main/java/com/wootech/dropthecode/domain/oauth/OauthAttributes.java, backend/src/main/java/com/wootech/dropthecode/domain/oauth/UserProfile.java, backend/src/main/java/com/wootech/dropthecode/dto/response/LoginResponse.java, backend/src/main/java/com/wootech/dropthecode/service/OauthService.java, backend/src/main/java/com/wootech/dropthecode/util/DataInitializer.java, backend/src/test/java/com/wootech/dropthecode/controller/AuthControllerTest.java, backend/src/test/java/com/wootech/dropthecode/controller/RestApiDocumentTest.java, backend/src/test/java/com/wootech/dropthecode/controller/auth/AuthenticationInterceptorTest.java, backend/src/test/java/com/wootech/dropthecode/domain/MemberTest.java, backend/src/test/java/com/wootech/dropthecode/domain/ReviewTest.java, backend/src/test/java/com/wootech/dropthecode/repository/ReviewRepositoryCustomImplTest.java, backend/src/test/java/com/wootech/dropthecode/service/AuthServiceTest.java, backend/src/test/java/com/wootech/dropthecode/service/MemberServiceTest.java
Member 도메인에 github url 추가 및 테스트 수정
코리부!
=> Member 도메인에 github url 추가 및 테스트 수정

backend/src/main/java/com/wootech/dropthecode/dto/response/MemberResponse.java, backend/src/main/java/com/wootech/dropthecode/dto/response/TeacherProfileResponse.java, backend/src/test/java/com/wootech/dropthecode/controller/MemberControllerTest.java, backend/src/test/java/com/wootech/dropthecode/service/MemberServiceTest.java
=> members/me, 리뷰어 상세 조회, 리뷰어 전체 조회 시 응답에 github url 필드 추가

frontend/src/__mock__/utils/mockingToken.ts, frontend/src/apis/auth.ts, frontend/src/components/Auth/AuthProvider/AuthProvider.tsx, frontend/src/components/Header/Header.test.tsx, frontend/src/hooks/useRevalidate.ts, frontend/src/utils/constants/key.ts
- token이 빈 값으로 갱신되지 않도록 조건문 추가
- 테스트 코드에 토큰관련 localStorage mocking data추가
- localStorage Key 상수화
=> token을 통한 로그인 유지 기능 오류 수정

frontend/src/__mock__/data/auth.ts, frontend/src/__mock__/data/reviews.ts, frontend/src/__mock__/server.ts, frontend/src/components/Header/Header.test.tsx, frontend/src/components/Reviewer/ReviewerFloatingBox/ReviewerFloatingBox.tsx, frontend/src/components/Reviewer/ReviewerInfoContainer/ReviewerInfoContainer.tsx, frontend/src/pages/ReviewerDetail/ReviewerDetail.test.tsx, frontend/src/setupTests.ts
- 리뷰어 상세정보 조회가 끝나면 상세정보를 확인할 수 있다.
- 리뷰 목록 확인하기 버튼을 클릭하면 리뷰 목록을 확인할 수 있다.
- 리뷰어가 나인경우 리뷰 요청하기 버튼이 리뷰 요청 버튼을 클릭할 수 없다.
- 리뷰어가 내가 아닌경우 리뷰 요청하기 버튼을 클릭할 수 있다.
=> 리뷰어 상세보기 페이지 테스트

frontend/src/__mock__/data/auth.ts, frontend/src/__mock__/data/reviews.ts, frontend/src/__mock__/server.ts, frontend/src/components/Header/Header.test.tsx, frontend/src/components/Review/ReviewRequest/ReviewRequest.test.tsx, frontend/src/components/Reviewer/ReviewerFloatingBox/ReviewerFloatingBox.tsx, frontend/src/components/Reviewer/ReviewerInfoContainer/ReviewerInfoContainer.tsx, frontend/src/pages/ReviewerDetail/ReviewerDetail.test.tsx, frontend/src/setupTests.ts
- 제목, pr 주소, 본문의 입력이 유효하지 않은 경우 요청을 보낼 수 없다.
- 모든 입력란이 유효한 경우 요청을 보낼 수 있다.
=> 리뷰 요청 컴포넌트 테스트

backend/src/main/java/com/wootech/dropthecode/util/DataInitializer.java
=> dummy data 수정

frontend/.storybook/preview.js, frontend/src/components/Transititon/Transition.tsx
Transition 컴포넌트의 Mount이후 Update가 비동기적으로 수행될 수 있도록 setTimeout을 추가하였습니다.
=> 컴포넌트의 상태 변경이 비동기적으로 일어나도록 변경

frontend/src/components/Auth/AuthProvider/AuthProvider.tsx, frontend/src/components/Review/ReviewInfoContainer/ReviewInfoContainer.tsx, frontend/src/components/Review/ReviewList/ReviewList.tsx, frontend/src/components/Review/ReviewRequest/ReviewRequest.tsx, frontend/src/components/Reviewer/ReviewerInfoContainer/ReviewerInfoContainer.tsx, frontend/src/hooks/useLanguageList.ts, frontend/src/hooks/useReviewerList.ts, frontend/src/pages/RedirectOAuth/RedirectOAuth.tsx, frontend/src/pages/ReviewerRegister/ReviewerRegister.tsx, frontend/src/utils/constants/key.ts
- 쿼리키 상수화
- 쿼리키에 파라미터가 누락된 부분 수정
=> 쿼리키 올바르게 수정

backend/src/main/java/com/wootech/dropthecode/exception/GlobalExceptionHandler.java, backend/src/main/java/com/wootech/dropthecode/repository/TeacherFilterRepositoryImpl.java
* skill과 관련된 inner join을 모두 left join으로 변경
=> 리뷰어 목록에서 리뷰어가 스킬을 갖고 있지 않은 경우 제외되는 버그 수정

backend/src/docs/asciidoc/api.adoc, backend/src/main/java/com/wootech/dropthecode/config/WebMvcConfig.java, backend/src/main/java/com/wootech/dropthecode/controller/MemberController.java, backend/src/main/java/com/wootech/dropthecode/service/TeacherService.java, backend/src/test/java/com/wootech/dropthecode/controller/MemberControllerTest.java, backend/src/test/java/com/wootech/dropthecode/controller/auth/AuthenticationInterceptorTest.java
=> 리뷰어 삭제 기능 구현

backend/src/docs/asciidoc/api.adoc, backend/src/main/java/com/wootech/dropthecode/config/WebMvcConfig.java, backend/src/main/java/com/wootech/dropthecode/controller/MemberController.java, backend/src/main/java/com/wootech/dropthecode/domain/TeacherProfile.java, backend/src/main/java/com/wootech/dropthecode/repository/bridge/TeacherLanguageRepository.java, backend/src/main/java/com/wootech/dropthecode/repository/bridge/TeacherSkillRepository.java, backend/src/main/java/com/wootech/dropthecode/service/TeacherLanguageService.java, backend/src/main/java/com/wootech/dropthecode/service/TeacherService.java, backend/src/main/java/com/wootech/dropthecode/service/TeacherSkillService.java, backend/src/test/java/com/wootech/dropthecode/controller/MemberControllerTest.java, backend/src/test/java/com/wootech/dropthecode/controller/auth/AuthenticationInterceptorTest.java
* 리뷰어 수정 기능 추가
* 없음
* title, content, carrer를 update하기 위해 setter 사용
=> 리뷰어 수정 기능 구현

backend/src/main/java/com/wootech/dropthecode/dto/response/TeacherProfileResponse.java, backend/src/main/java/com/wootech/dropthecode/repository/TeacherFilterRepositoryImpl.java
쿼리 문으로 정렬하고 싶었지만 JPQL은 JOIN 문 안에서의 서브 쿼리가 불가능하기 때문에, 쿼리를 날려 결과값을 받아온 후 DTO에서 정렬하도록 구현.
https://stackoverflow.com/questions/6942108/jpql-querydsl-join-subquery-and-get-aliased-column
=> 언어 및 기술 스택 정렬

backend/src/main/java/com/wootech/dropthecode/exception/GlobalExceptionHandler.java, backend/src/main/resources/appender/error-file-appender.xml, backend/src/main/resources/appender/info-file-appender.xml, backend/src/main/resources/logback-spring.xml
* Custom Exception이 errror 로깅이 되지 않던 오류를 수정
=> custom exception에 대한 로깅을 추가

backend/src/main/java/com/wootech/dropthecode/service/ReviewService.java
=> 리뷰 생성시 PENDING 상태로 생성

frontend/src/apis/review.ts, frontend/src/components/Review/ReviewEdit/ReviewEdit.tsx, frontend/src/components/Review/ReviewFeedback/ReviewFeedback.tsx, frontend/src/components/Review/ReviewInfoContainer/ReviewInfoContainer.tsx, frontend/src/hooks/useReview.ts, frontend/src/types/review.d.ts, frontend/src/utils/constants/message.ts
지옥의 분기가 들어간 코드입니다 (주의)
커스텀 훅(useReview)을 통해 비즈니스 로직을 분리했습니다.
=> 리뷰 상태 갱신 및, 수정 삭제 기능 구현

frontend/src/components/Auth/AuthRoute/AuthRoute.tsx, frontend/src/pages/ReviewerRegister/ReviewerRegister.tsx, frontend/src/utils/constants/message.ts
리뷰어인 경우 리뷰어 등록페이지 접근시 메인페이지로 리다이렉션
=> 리뷰어 등록페이지 리다이렉트 추가

frontend/babel.config.js, frontend/src/components/Review/ReviewFeedback/ReviewFeedback.stories.tsx, frontend/src/components/Review/ReviewFeedback/ReviewFeedback.tsx
- builtins: false값으로 수정 [minify plugin issue](https://github.com/babel/minify/issues/904)
3년전 이슈인데 해결되지 않고, 남겨져있어 플러그인에 대한 discussion이 필요해보임
- (스토리북 관련) 추가로 컴파일할 때 에러가 있음에도 불구하고 merge까지 진행되었는데 이 부분에 대해서 보완할 방법이 필요
=> minify 플러그인 옵션 및 오류 수정

backend/src/main/resources/application-prod.properties
운영환경 refresh token expire time 2주로 설정
=> 운영환경 refresh token expire time 2주로 설정

backend/src/main/java/com/wootech/dropthecode/controller/ReviewController.java, backend/src/main/java/com/wootech/dropthecode/domain/LoginMember.java, backend/src/main/java/com/wootech/dropthecode/service/ReviewService.java, backend/src/test/java/com/wootech/dropthecode/controller/ReviewControllerTest.java, backend/src/test/java/com/wootech/dropthecode/domain/LoginMemberTest.java, backend/src/test/java/com/wootech/dropthecode/service/ReviewServiceTest.java
- 로그인 한 멤버와 '내가 받은 리뷰' 조회 학생 id가 다른경우 예외처리 추가
=> 로그인 한 멤버와 '내가 받은 리뷰' 조회 학생 id가 다른경우 예외처리 추가

backend/build.gradle, backend/src/main/java/com/wootech/dropthecode/config/CustomDataSourceConfig.java, backend/src/main/java/com/wootech/dropthecode/config/WebMvcConfig.java, backend/src/main/java/com/wootech/dropthecode/domain/CustomDataSourceProperties.java, backend/src/main/java/com/wootech/dropthecode/repository/replication/CircularList.java, backend/src/main/java/com/wootech/dropthecode/repository/replication/CustomDataSourceProperties.java, backend/src/main/java/com/wootech/dropthecode/repository/replication/ReplicationRoutingDataSource.java, backend/src/main/java/com/wootech/dropthecode/service/AuthService.java, backend/src/main/java/com/wootech/dropthecode/service/FeedbackService.java, backend/src/main/java/com/wootech/dropthecode/service/LanguageService.java, backend/src/main/java/com/wootech/dropthecode/service/SkillService.java, backend/src/main/java/com/wootech/dropthecode/service/TeacherLanguageService.java, backend/src/main/java/com/wootech/dropthecode/service/TeacherSkillService.java, backend/src/main/resources/application-dev.properties, backend/src/main/resources/application-local-init.properties, backend/src/main/resources/application-local.properties, backend/src/main/resources/application-prod.properties, backend/src/main/resources/application-test.properties, backend/src/main/resources/logback-spring.xml
* https://github.com/woowacourse-teams/2021-drop-the-code/wiki/DB-Replication-Spring-Boot-%EC%A0%81%EC%9A%A9
=> DB Replication 스프링 부트 적용

backend/src/main/java/com/wootech/dropthecode/controller/auth/util/JwtTokenProvider.java, backend/src/main/java/com/wootech/dropthecode/service/MemberService.java, backend/src/test/java/com/wootech/dropthecode/acceptance/AcceptanceTest.java
=> 주석 & 사용하지 않는 부분 제거 

frontend/src/components/Review/ReviewCard/ReviewCard.tsx, frontend/src/hooks/useReview.ts, frontend/src/utils/constants/progress.ts
=> 리뷰 카드 progress 상태 수정

frontend/babel.config.js
=> NODE_ENV 에러 처리

backend/src/main/resources/logback-access.xml, backend/src/main/resources/logback-spring.xml
* prod profile만 로깅하고 있는 상태에서 dev profile 추가
=> 로깅 profile에 dev 추가

backend/src/main/java/com/wootech/dropthecode/util/DataInitializer.java
* DataInitializer profile 중 prod-init에 삭제
=> feat: 더미 데이터 운영 서버에서 제외

backend/src/main/java/com/wootech/dropthecode/config/CacheConfig.java, backend/src/main/resources/application-test.properties
* password 설정이 없어 redis 접속 실패
* password 설정 추가
=> Redis password 설정 추가

backend/src/main/java/com/wootech/dropthecode/domain/chatting/Chat.java, backend/src/main/java/com/wootech/dropthecode/domain/chatting/Room.java, backend/src/main/java/com/wootech/dropthecode/dto/response/LatestChatResponse.java, backend/src/main/java/com/wootech/dropthecode/service/ChattingService.java
=> ChatResponse DTO에 roomId필드 추가
